name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    
    # Step 4: Run Flask application
    - name: Run the Flask app
      run: |
        make run &
        # Sleep to allow Flask server to start
        sleep 10


    # Step 6: Run additional tests (optional)
    # If you have unit tests, they can be run here.
    # Uncomment if you add tests in the future.
    #
    # - name: Run tests
    #   run: pytest
